### ISSUE TITLE
Chose a Safe

### ISSUE THREAD

**Issue by jdoclot** [online-net/c14-cli#10]
Hi,

Can you implement a command that can choose where we want to store an archive?

Thanks

**Comment by egurelli** [comment]
Well c14 tool working nicely, thanks. On online.net api something like

`POST /storage/c14/safe/{safe_id}/archive Create an archive`

exists.  Is this cli "proxy" to api?

**Comment by coolya** [comment]
With #14 this is now possible.

**Comment by Solvik** [comment]
Thanks to @coolya  it's fixed, I'm closing the issue
