### ISSUE TITLE
Add the scrub feature

### ISSUE THREAD

**Issue by Solvik** [online-net/c14-cli#11]
The API exposes a feature to verify (scrub) an archive
We should implement it

/storage/c14/safe/{safe_id}/archive/{archive_id}/location/{location_id}/verify

**Comment by QuentinPerez** [comment]
I added a new subcommand for your needs `verify`  https://github.com/online-net/c14-cli/commit/a876657b477c6fa5217a8c5f0ac633d0ddb5f647

**Comment by Solvik** [comment]
:heart:
