### ISSUE TITLE
Rate limiting?

### ISSUE THREAD

**Issue by coolya** [online-net/c14-cli#23]
Starting last weekend I was getting 503 responses from the online.net api when I used c14. Especially when creating new safes. I created a ticket at online.net because I thought I was a problem with api backend. I was then told that this was causes because of rate limiting and that I was polling the api to often. Since I haven't changed anything in c14 with regard to that I'm not sure what caused this.

Is there something we can do in the client to prevent this?

The internal ticket id is #510273 if that helps. 

Traces essentially looked like this:

```
./c14 --debug create --name=test6
 DEBUG[0000] [GET]: https://api.online.net/api/v1/user/key/ssh
 DEBUG[0000] [Response]: [200] [{"uuid_ref":"226e8a7f-b267-421c-9b96-d71bcb595135","description":"gitlab","fingerprint":"11:93:ff:c6:6c:aa:ad:f7:50:eb:89:90:d0:22:95:b3"}]
 DEBUG[0000] [POST]: https://api.online.net/api/v1/storage/c14/safe
 DEBUG[0000] [Response]: [201] {"uuid_ref":"bec8e55b-cd5f-46b4-a512-dfa51c1a3b3a"}
 DEBUG[0000] [GET]: https://api.online.net/api/v1/storage/c14/safe/bec8e55b-cd5f-46b4-a512-dfa51c1a3b3a
 DEBUG[0001] [Response]: [200] {"$ref":"\/api\/v1\/storage\/c14\/safe\/bec8e55b-cd5f-46b4-a512-dfa51c1a3b3a","uuid_ref":"bec8e55b-cd5f-46b4-a512-dfa51c1a3b3a","name":"test6_safe","status":"active","description":""}
 DEBUG[0001] [POST]: https://api.online.net/api/v1/storage/c14/safe/bec8e55b-cd5f-46b4-a512-dfa51c1a3b3a/archive
 DEBUG[0001] [Response]: [503] <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

 FATAL[0001] /Users/kdummann/go/src/github.com/online-net/c14-cli/pkg/api/api.go:179: [503] <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

/Users/kdummann/go/src/github.com/online-net/c14-cli/pkg/api/methods.go:186: CreateArchive
/Users/kdummann/go/src/github.com/online-net/c14-cli/pkg/api/helpers.go:56: CreateSSHBucketFromScratch:CreateArchive
/Users/kdummann/go/src/github.com/online-net/c14-cli/pkg/commands/create.go:97: Run:CreateSSHBucketFromScratch
```

**Comment by Solvik** [comment]
Hi @coolya,

I'm sorry you're facing this issue.
We've been having a lot of requests on the C14 API and had no other solutions than massively rate limiting requests to the API to preserve all the other services.

I'm personally handling with my team scaling issues.
We've been able to improve the rate limiting based on the Authorization token.
We're adding API servers and should restore a full service early next week.

**Comment by Solvik** [comment]
with the last commit and new servers in the API pool, you should no longer get rate limited.

**Comment by coolya** [comment]
Thanks a lot for you work on that! The issues seems to be gone.

**Comment by coolya** [comment]
One suggestion for improvement: If the 503 would include a more verbose error message that the request was rejected because of rate limiting and/or that this is temporary because of the high load would be very useful.

**Comment by Solvik** [comment]
We've changed the HTTP return code to 429 and added a message about the rate limiting. Also added a few headers giving the number of request available, left and till when.

**Comment by coolya** [comment]
👍
