### ISSUE TITLE
Add command to return safe deposit box connection details

### ISSUE THREAD

**Issue by maticmeznar** [online-net/c14-cli#31]
Hey, would it be possible to add a command that would return username, password, host and port for a safe deposit box with given UUID? Optionally, a flag could be used to also set ENV variables with returned values. Also, this could be an option for "create" command, returning everything you need to connected to a newly created safe deposit box.

This would greatly simplify using c14 with rsync, sshfs, davfs, etc.

**Comment by agirot** [comment]
#33 Done with JSON output if you want easily parse return.

**Comment by maticmeznar** [comment]
@agirot Nice! Would it be possible to also have `port` and `host` keys in the map, so they don't have to be extracted from `uri`?
