### ISSUE TITLE
ssh: must specify HostKeyCallback

### ISSUE THREAD

**Issue by gonzague** [online-net/c14-cli#36]
Hi
When trying to upload via C14 CLI I get this error .. 
`root@vrayo:~# c14 upload /etc/ 6cd0ab4e-xxxx-4fe8-8207-0614fc5f494b`
`FATAL[0000] ssh: must specify HostKeyCallback
`
Host runs Ubuntu 16.04.2 LTS 
Go version : go version go1.6.2 linux/amd64

Any idea on how to fix this ? :)

thanks

Gonzague

**Comment by ardaozkal** [comment]
go 1.8.1 on arch linux here.

Can repro :/

**Comment by flemzord** [comment]
You do not have a specific configuration in your ssh? .ssh/config file

@gonzague

**Comment by ardaozkal** [comment]
@flemzord I do not. I wasn't told to do that.

**Comment by QuentinPerez** [comment]
@agirot can you fix it ?

**Comment by gonzague** [comment]
@flemzord : nope super basic setup

**Comment by agirot** [comment]
@gonzague Can you pull and try again plz ? (#34)

**Comment by ardaozkal** [comment]
Confirmed fixed here.

**Comment by gonzague** [comment]
Fixed :) thanks
