### ISSUE TITLE
Can't create archive in existing safe

### ISSUE THREAD

**Issue by gonzague** [online-net/c14-cli#37]
`root@vrayo:~# c14 create --safe "MySafe" 
 FATAL[0000] [409] : This name is already used
`
When trying to create an archive in a safe which already exists ( because c14 create without a safe name creates a new safe each time which I dont want) ... it fails :( 

What is the expected behaviour ?
I would like to do `c14 create --name "MyArchive" --description "A new archive" --safe `"MySafe"`` where MySafe already exists and this adds an archive to this safe 

thanks !

**Comment by domi007** [comment]
Same error here as well, pretty annoying I need to say...

**Comment by domi007** [comment]
At least after some debugging I was able to fix it:
Changing `o.GetSafes(true);` on this line to `o.GetSafes(false);` disables the use of cache and fixes the issue of trying to create an already existing safe
https://github.com/online-net/c14-cli/blob/master/pkg/api/helpers.go#L31

**Comment by agirot** [comment]
done #40
