### ISSUE TITLE
Progress output should go to stderr, not stdout.

### ISSUE THREAD

**Issue by ardaozkal** [online-net/c14-cli#39]
I'm trying to get the create output to a variable so I can upload to it from a script, but the output is a mess:
`$'\r'-$'\r'$'\r'\\$'\r'$'\r'\|$'\r'$'\r'/$'\r'$'\r'-$'\r'$'\r'-$'\r'$'\r'\\$'\r'$'\r'\|$'\r'$'\r'/$'\r'$'\r'-$'\r'$'\r'-$'\r'$'\r'\\$'\r'$'\r'\|$'\r'$'\r'/$'\r'$'\r'-$'\r'$'\r'-$'\r'$'\r'\\$'\r'$'\r'\|$'\r'$'\r'/$'\r'$'\r'-$'\r'$'\r'-$'\r'$'\r'\\$'\r'$'\r'\|$'\r'$'\r'/$'\r'$'\r'-$'\r'$'\r'-$'\r'$'\r'\\$'\r'$'\r'\ $'\r'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa`

uuid was replaced with a's for potential security reasons.

This makes scripting an unnecessary pain, and is probably a bug. 

Here's what Ask Ubuntu General Room has to say: `It looks like a progress spinner of sorts, the output` - `Ah! Yes. And the idiots are printing it to stdout.` - `Ask them to print progress reports to stderr where they belong.`

**Comment by ardaozkal** [comment]
Upon further digging in code, I found 2 stuff:

1) The spinning status output: https://github.com/online-net/c14-cli/blob/master/pkg/api/helpers.go#L90

it should go to stderr, not stdout.

2) there's apparently a quiet flag: https://github.com/online-net/c14-cli/blob/master/pkg/commands/create.go#L42

But it's not documented on `c14 --help`:

![](https://s.ave.zone/b95.png)

**Comment by ardaozkal** [comment]
Ok, my second point of `--help` not showing is due to me adding --help in middle...

that's weird. Meh.

**Comment by agirot** [comment]
Step 1 : `Run 'c14 COMMAND --help' for more information on a command.`
Step 2 : `c14 create --help`

> -q, --quiet=false     Don't display the waiting loop

it's pretty simple i think, no ? :)
