### ISSUE TITLE
Value for 'parity' on the command line 'c14 create'

### ISSUE THREAD

**Issue by ilanmimoun** [online-net/c14-cli#47]
What is value for the option `parity` on the command line `c14 create`? For `standard`, `intensive` or `enterprise`.

**Comment by Daverball** [comment]
They're exactly that, so `standard`, `intensive` and `enterprise` from what I can tell. I've only ever used `intensive` but that wasn't documented either.

**Comment by ilanmimoun** [comment]
Ok thanks.
