### ISSUE TITLE
Equivalent of the 4 operations in CLI

### ISSUE THREAD

**Issue by ilanmimoun** [online-net/c14-cli#49]
There is 4 operations: Archiving, Unarchiving, Destruction and Verification.
What is the equivalent of these CLI operations?
I guess, Archiving is "c14 freeze".
I guess, Unarchiving is "c14 unfreeze".
I guess, Destruction is "c14 remove".
But, which one is for Verification?

**Comment by Daverball** [comment]
The documentation isn't up to date, the master branch has a few things added since the last release, including the verify command, which is `c14 verify`.

**Comment by ilanmimoun** [comment]
Great, thanks.
